name: some_application
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  line_icons: ^2.0.0
  # Rest API
  dio: ^4.0.3
  http: ^0.13.4
  # Show errors
  # fluttertoast: ^8.0.8
  # Freezed
  freezed_annotation: ^0.14.1
  # Cool alert
  cool_alert: ^1.1.0
  # Hyperlink 
  url_launcher: ^6.0.6
  # Svg images
  flutter_svg: ^0.22.0
  # TextFormField which format the input by a given mask.
  mask_text_input_formatter: ^2.0.0
  # Provider state management
  provider: ^6.0.1
  # Internet connectivity
  connectivity: ^3.0.6
  # Wraps platform-specific persistent storage for simple data
  shared_preferences: ^2.0.8
  # onboarding
  animated_onboarding: ^0.0.2
  #bottom navigation bar
  scroll_bottom_navigation_bar: ^4.0.0
  # bottom nav bar
  animated_bottom_navigation_bar: ^0.3.2
  # rive animation
  # rive: ^0.8.1
  #carousel
  carousel_slider: ^4.0.0
  # modal hud progress
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  # translator/localization
  # easy_localization: ^3.0.0
  # datepicker
  syncfusion_flutter_datepicker: ^19.2.47
  # share 
  flutter_share: ^2.0.0
  google_fonts: ^2.3.1

dev_dependencies:
  # build_runner:
  # freezed: ^0.14.1+1
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^0.1.3
  percent_indicator: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/svg/
    - assets/images/png/
    # - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
